# Generated by Django 2.1.1 on 2018-09-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seat_empty', models.CharField(max_length=200)),
                ('seat_num', models.IntegerField(default=0)),
            ],
        ),
    ]
